# Generated by Django 4.2.16 on 2024-09-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='asiakas', max_length=50)),
                ('address', models.CharField(default='asiakas', max_length=100)),
                ('phone', models.CharField(default='asiakas', max_length=20)),
                ('email', models.CharField(default='asiakas', max_length=50)),
                ('country', models.CharField(default='asiakas', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='toyota', max_length=30)),
                ('model', models.CharField(default='yaris', max_length=30)),
                ('licenseplate', models.CharField(default=3, max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.supplier')),
            ],
        ),
    ]
